### ISSUE TITLE
Revisit how to stop the DataLoader thread

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-widgets#3]
Two things about this, per @ronpandolfi:

https://github.com/bluesky/bluesky-widgets/blob/38b7f1aa6c26a4b9e59a71acfdc446a377755bca/bluesky_widgets/qt/search_results.py#L91

* Don't use `terminate`. Take the approach (which we use a lot in caproto) of setting an `Event` that we check on periodically. Add a timeout for the `get()`.
* Connect setting this `Event` to both `destroyed` _and_ `QApplication.aboutToQuit`.

**Comment by cryos** [comment]
It would be good to get more information on why connecting this `Event` to `destroyed` and `QApplication.aboutToQuit`. I fully concur with never calling `terminate` or similar in reusable code like this. More detail would be useful on the reason for wanting more connections here.

**Comment by ronpandolfi** [comment]
One thought is that in some scenarios you can't guarantee the order of destruction. For example, QApplication.quit(). If the QThread gets destroyed first its already too late? In this case the thread also needs to be cleaned up if its related widget is destroyed (as when the widget is disowned or queued for deletion). So, I think both are good.

**Comment by cryos** [comment]
If we get the ownership right, and ensure deleteLater is used then it should allow anything listening for destruction to clean up before the thread is destroyed. Can you maybe go into a little more detail about what you are worried about here more concretely? The parenting in combination with the event loop and deleteLater are normally enough, I don't think I see why the outer application needs to worry about the background thread to be honest.

**Comment by danielballan** [comment]
> If we get the ownership right

I think this is the key point, and something I had _not_ got right in #4 until just now.

> One thought is that in some scenarios you can't guarantee the order of destruction

The order of destruction is guaranteed as long as the object has a `parent`: Qt walks down the tree from parents to children when it destroys things.

New commits in #4 make the `DataLoader` a child of `_SearchResultsModel`, so we know that `_SearchResultsModel` will get destroyed first, and code has been added to gracefully stop `DataLoader` (and block on its successful stopping) before Qt can get around to destroying it.

**Comment by cryos** [comment]
Thanks for sticking with it @danielballan, I learned quite a bit about mapping the Qt C++ object lifetimes to Python!

**Comment by danielballan** [comment]
To be continued in https://github.com/bluesky/bluesky-widgets/issues/7 but think we have something we can move forward with for now.
