### ISSUE TITLE
Avoid the name func; use something more descritive.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-widgets#47]
@jklynch has convinced me we should avoid `func` in public API:

> My objection to "func" is that it is kind of like naming a variable "string" or "float".

> [It's] not so much that I want "great names" but I want each line to convey information about what's going on.

In our case, we are using a user-provided (or default) function to transform data into whatever we want to plot. Maybe `transform` would be good here. I am used to seeing `func` for this, as in the follow example from pandas, but I think a more descriptive name would be better if we can agree on one.

In [1]: import pandas

In [2]: df = pandas.DataFrame({'a': [1,2,3]})

In [3]: g = df.groupby('a')

```
In [4]: g.apply?
Signature: g.apply(func, *args, **kwargs)
Docstring:
Apply function `func` group-wise and combine the results together.

The function passed to `apply` must take a dataframe as its first
argument and return a DataFrame, Series or scalar. `apply` will
then take care of combining the results back together into a single
dataframe or series. `apply` is therefore a highly flexible
grouping method.

While `apply` is a very flexible method, its downside is that
using it can be quite a bit slower than using more specific methods
like `agg` or `transform`. Pandas offers a wide range of method that will
be much faster than using `apply` for their specific purposes, so try to
use them before reaching for `apply`.

Parameters
----------
func : callable
    A callable that takes a dataframe as its first argument, and
    returns a dataframe, a series or a scalar. In addition the
    callable may take positional and keyword arguments.
args, kwargs : tuple and dict
    Optional positional and keyword arguments to pass to `func`.
```

**Comment by jklynch** [comment]
I think `transform` is good because it suggests a numerical operation, or at least an operation on numbers that results in a number or numbers.

**Comment by danielballan** [comment]
This is partly moot, as `func` has vanished from the public API for other reasons, but we do now use `_transform` internally where we might have used `func` before. Therefore, closing.
