### ISSUE TITLE
Add a text search box to SearchInput

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-widgets#59]
This should search the `$text` index of the 'start' documents, just as `db.v1("search term")` does.

**Comment by danielballan** [comment]
The model for `SearchInput` will need to grow a new `property` and a new item in the `EmitterGroup`, probably called `text`.

https://github.com/bluesky/bluesky-widgets/blob/7dbe644d5cc2c2fdb7831650fe76d6025aadcbe6/bluesky_widgets/models/search.py#L255-L267

It will need a new method that fires when `text` changes and updates the MongoDB `query` accordingly. It will be similar to what we do with `on_since` or `on_until`, but simpler because we won't have to do all the time-related stuff:

https://github.com/bluesky/bluesky-widgets/blob/7dbe644d5cc2c2fdb7831650fe76d6025aadcbe6/bluesky_widgets/models/search.py#L337-L349

It should add a [MongoDB text query](https://docs.mongodb.com/manual/reference/operator/query/text/) to the query dictionary.

It should be possible to test the model alone like this:

```py
In [10]: from bluesky_widgets.models.search import SearchInput

In [11]: s = SearchInput()

In [12]: from datetime import datetime

In [13]: s.events.query.connect(lambda event: print("New query:", event.query))
Out[13]: <function __main__.<lambda>(event)>

In [14]: s.since = datetime(2000, 1, 1)
New query: {'time': {'$gte': 946702800.0}}

In [15]: s.until = datetime(1985, 11, 15)
New query: {'time': {'$gte': 500878800.0, '$lt': 500878800.0}}

In [16]: s.query
Out[16]: {'time': {'$gte': 500878800.0, '$lt': 500878800.0}}
```

by setting `s.text = "..."`.

Once that works, an input field will need to be added to https://github.com/bluesky/bluesky-widgets/blob/master/bluesky_widgets/qt/_search_input.py, following the patterns in that file.

Finally the app can be tested by running this example:

```
python -m bluesky_widgets.examples.qt_search
```

**Comment by bsobhani** [comment]
I have a db of type databroker._core.Broker. If I type db("a") I get the following error message:

```
~/miniconda3/envs/bluesky-widgets/lib/python3.8/site-packages/mongoquery/__init__.py in _not_implemented(*_)
    115     @staticmethod
    116     def _not_implemented(*_):
--> 117         raise NotImplementedError
    118
    119     @staticmethod

NotImplementedError:
```

Is there a certain version of mongoquery I need to have installed?

**Comment by danielballan** [comment]
Ah, I had not realized that `$text` queries are not supported by mongoquery. We may need actual MongoDB to test this. This [example](https://github.com/bluesky/databroker/blob/master/examples/generate_mongo_data.py) creates a MongoDB-backed Catalog (a.k.a Broker) with some example data and may be suitable for testing.

**Comment by danielballan** [comment]
So, you would take the `catalog` from my example above and plug it into this line:

https://github.com/bluesky/bluesky-widgets/blob/7dbe644d5cc2c2fdb7831650fe76d6025aadcbe6/bluesky_widgets/examples/qt_search.py#L71

in place of `get_catalog()`.

**Comment by danielballan** [comment]
Ideally we should run examples/demos/tests like this on samples of real beamline data. We are building up a collection of openly-licensed representative data samples at https://github.com/bluesky/data-samples but if you try that at this moment it won't work at all. Still a work in progress.
