### ISSUE TITLE
Confirm that QThreads are actually closing themselves

### ISSUE THREAD

**Issue by ronpandolfi** [bluesky/bluesky-widgets#9]
In response to #4 , I'm not confident that connecting a signal directly to requestInterruption works without an event loop in the worker thread. We could either confirm this is working or instead bind to a method on the parent widget to call `thread.requestInterruption()`

There is some good discussion of the tricks inherent to QThreads here:
https://wiki.qt.io/Threads_Events_QObjects

(See "DOs and DON'Ts" and Per-thread event loop)

Also fun:
https://woboq.com/blog/qthread-you-were-not-doing-so-wrong.html

**Comment by danielballan** [comment]
Thanks. My only evidence that this is working is some DEBUG prints, which is not sufficient to prove that it _always_ works. It might have been "winning a race" in the cleanup race conditions.

Seems best to adopt modern practices and avoid `QThread` entirely unless/until we actually need it in #10
